const router = require("express").Router();
const { postsController } = require("../controllers");
const { uploadImageMiddleware, authMiddleware } = require("../middlewares");
const { uploadImage } = uploadImageMiddleware;
const { auth } = authMiddleware;
router.post("/",auth, postsController.createPosts);
router.get("/", postsController.getPost);
router.put("/:postId", auth, postsController.updatePost);
router.delete("/:postId", auth, postsController.deletePosts);
module.exports = router;
